#!/usr/bin/env bash
# Abrir el archivo /etc/passwd y leerlo línea por línea
while IFS=: read -r username _ user_id _ _ home_directory _; do
	echo "$username:$user_id:$home_directory"
done < /etc/passwd