#!/usr/bin/env bash
# Leer el archivo /etc/passwd línea por línea
while IFS=: read -r username password user_id group_id _ home_directory shell; do
  # Formatear y mostrar la información según el formato requerido
  echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
