#!/usr/bin/env bash
# Agrupa visitantes por IP y código HTTP, y muestra los datos en el formato requerido
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
