#!/usr/bin/env bash
# Usar awk para procesar el archivo de registro de Apache
awk '{
    ip_status[$1 " " $9]++
}
END {
    for (i in ip_status) {
        print ip_status[i], i
    }
}' apache-access.log | awk '
{
    count[NR] = $0
}
END {
    n = asorti(count, sorted)
    for (i = n; i >= 1; i--) {
        print count[sorted[i]]
    }
}'
