#!/bin/bash
# Usar awk para procesar el archivo de registro de Apache, contar y ordenar los resultados
awk '{count[$1, $9]++} END {for (combo in count) {split(combo, arr, SUBSEP); print count[combo], arr[1], arr[2]}}' apache-access.log | sort -nr