#!/usr/bin/env bash
#Y u no love me
terminate() {
    echo "I hate the kill command"
    cleanup
    exit 1
}

# Function to handle SIGINT signal
interrupt() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit() {
    echo "Received SIGQUIT or SIGTERM. Terminating..."
    cleanup
    exit 0
}

# Function to cleanup and delete PID file
cleanup() {
    echo "Cleaning up and deleting PID file..."
    rm -f /var/run/myscript.pid
}

# Trap signals and associate them with corresponding functions
trap terminate SIGTERM
trap interrupt SIGINT
trap quit SIGQUIT

# Get PID and store it in the file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done