#!/usr/bin/env bash
# Este script muestra el PID y el nombre del proceso de los procesos cuyo nombre contiene la palabra "bash"

for pid in $(ls /proc | grep '^[0-9]*$'); do
    if [[ -f /proc/$pid/cmdline ]]; then
        cmd=$(cat /proc/$pid/cmdline | tr '\0' ' ' | grep -o 'bash')
        if [[ $cmd == "bash" ]]; then
            echo "$pid bash"
        fi
    fi
done
