#!/usr/bin/env bash
# Este script detiene el proceso 4-to_infinity_and_beyond

# Obtener el PID del proceso 4-to_infinity_and_beyond
pid=$(pgrep -f "bash ./4-to_infinity_and_beyond")

# Enviar la señal TERM para detener el proceso
kill "$pid"
